#!/bin/bash

echo "🔧 Generating encryption key for production..."
python3 -c "from cryptography.fernet import Fernet; print('ENCRYPTION_KEY=' + Fernet.generate_key().decode())"

echo ""
echo "🔑 Copy the above ENCRYPTION_KEY to your Render environment variables"
echo ""
echo "📝 Also set these environment variables in Render:"
echo "   - GROQ_API_KEY: Your Groq API key from console.groq.com"
echo "   - JWT_SECRET_KEY: (auto-generated by Render)"
echo "   - CORS_ORIGINS: Your frontend URL (e.g., https://aidevs-frontend.onrender.com)"
